# Avance 2. Ingeniería de características

## Objetivos
2.3 Crear nuevas características para mejorar el rendimiento de los modelos.

2.4 Mitigar el riesgo de características sesgadas y acelerar la convergencia de algunos algoritmos.

### Librerías y Carga de Datos

#### Librerías

In [4]:
import pandas as pd
import numpy as np

#### Carga de Datos

In [3]:
path = '../../data/processed/data.parquet'
df = pd.read_parquet(path)
df.head()

,Fecha,Cuadro,Estado,Codigo Padecimiento,Ax_003,Año,Semana,Ax_001,Ax_002,Valor,Padecimiento,Mes
0,2014-01-06,CUADRO 17.,Aguascalientes,F32,Sem.,2014,2,2014.0,0,1.0,DepresiónCIE-10ª REV.F32,1
1,2014-01-13,CUADRO 17.,Aguascalientes,F32,Sem.,2014,3,2014.0,0,2.0,DepresiónCIE-10ª REV.F32,1
2,2014-01-20,CUADRO 17.,Aguascalientes,F32,Sem.,2014,4,2014.0,0,1.0,DepresiónCIE-10ª REV.F32,1
3,2014-01-27,CUADRO 17.,Aguascalientes,F32,Sem.,2014,5,2014.0,0,1.0,DepresiónCIE-10ª REV.F32,1
4,2014-02-03,CUADRO 17.,Aguascalientes,F32,Sem.,2014,6,2014.0,0,2.0,DepresiónCIE-10ª REV.F32,2

#### Operaciones Comunes

##### Generación de nuevas características

###### Fechas de pandemia por COVID-19

In [5]:
# Generar columna de temporada de COVID
# Definir el rango de fechas de la pandemia
covid_start = pd.to_datetime('2020-03-01')
covid_end = pd.to_datetime('2022-03-31')

if 'Fecha' in df.columns:
    df['Fecha'] = pd.to_datetime(df['Fecha'])
    df['temporada_covid'] = np.where((df['Fecha'] >= covid_start) & (df['Fecha'] <= covid_end), 1, 0)
else:
    print('No se encontró la columna "Fecha" en el DataFrame.')

df.head()

,Fecha,Cuadro,Estado,Codigo Padecimiento,Ax_003,Año,Semana,Ax_001,Ax_002,Valor,Padecimiento,Mes,temporada_covid
0,2014-01-06,CUADRO 17.,Aguascalientes,F32,Sem.,2014,2,2014.0,0,1.0,DepresiónCIE-10ª REV.F32,1,0
1,2014-01-13,CUADRO 17.,Aguascalientes,F32,Sem.,2014,3,2014.0,0,2.0,DepresiónCIE-10ª REV.F32,1,0
2,2014-01-20,CUADRO 17.,Aguascalientes,F32,Sem.,2014,4,2014.0,0,1.0,DepresiónCIE-10ª REV.F32,1,0
3,2014-01-27,CUADRO 17.,Aguascalientes,F32,Sem.,2014,5,2014.0,0,1.0,DepresiónCIE-10ª REV.F32,1,0
4,2014-02-03,CUADRO 17.,Aguascalientes,F32,Sem.,2014,6,2014.0,0,2.0,DepresiónCIE-10ª REV.F32,2,0

##### Discretización o binning

##### Codificación (ordinal, one hot,…)

##### Escalamiento (normalización, estandarización, min – max,…)

##### Transformación (logarítmica, exponencial, raíz cuadrada, Box – Cox, Yeo – Johnson,…)

#### Métodos de filtrado

In [ ]:
# ¿Se realizará algún filtrado o PCA considerando que no tenemos tantos datos?

#### Conclusiones